---
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - defaults/main.yml
  vars:
    vimrc_ansible_managed: true
    vim_install_plugins: true
    zsh_ansible_managed: true
    zsh_editor: "vim"
  tasks:
    - include: tasks/golang.yml
